### ISSUE TITLE
FourDisplay driver

### ISSUE THREAD

**Issue by valoni** [bauland/TinyClrLib#1]
tested this drivers (everything work well until using DOTS)

problem appear if used 0x80 check this code to understand problem 

///
          bool point=true;

            FourDigitDisplay fdd = new FourDigitDisplay(Fez.Gpio.D3, Fez.Gpio.D4);
            fdd.SetBrightness(FourDigitDisplay.Brightness.Pw01);

            while (true)
            {
                for (int d1 = 0; d1 < 10; d1++)
                    for (int d2 = 0; d2 < 10; d2++)
                        for (int d3 = 0; d3 < 10; d3++)
                            for (int d4 = 0; d4 < 10; d4++)
                            { 
                                //show point 
                                fdd.SetPoint(point);  
                               /* if point = true  than number 4 appear as 9 and . number 1 appear as 7   
                                   if point = false everything was ok seem problem appear on SHIFT LEFT ..
                                */
                                
                                //show values 
                                fdd.Display(d1,d2,d3,d4);

                                point = !point;
                                Thread.Sleep(350);
                            }
            }

**Comment by valoni** [comment]
on BrainPad it run well

**Comment by bauland** [comment]
Seems to be come from only port of nucleo 411
